### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Renaud11232** [Renaud11232/OctoPrint-Marlin-Flasher#22]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x34 pc=0x37c600]
 
goroutine 1 [running]:
github.com/arduino/arduino-cli/arduino/cores.(*PlatformRelease).GetLibrariesDir(0x0, 0x3)
    /__w/arduino-cli/arduino-cli/arduino/cores/cores.go:210 +0x2c
github.com/arduino/arduino-cli/arduino/libraries/librariesmanager.(*LibrariesManager).AddPlatformReleaseLibrariesDir(0x2913d60, 0x0, 0x2)
    /__w/arduino-cli/arduino-cli/arduino/libraries/librariesmanager/librariesmanager.go:143 +0x20
github.com/arduino/arduino-cli/legacy/builder.(*LibrariesLoader).Run(0xcd429c, 0x1040960, 0xcd429c, 0x0)
    /__w/arduino-cli/arduino-cli/legacy/builder/libraries_loader.go:62 +0x444
github.com/arduino/arduino-cli/legacy/builder.(*ContainerSetupHardwareToolsLibsSketchAndProps).Run(0xcd429c, 0x1040960, 0xcd429c, 0x10)
    /__w/arduino-cli/arduino-cli/legacy/builder/container_setup.go:60 +0x1f0
github.com/arduino/arduino-cli/legacy/builder.runCommands(0x1040960, 0x130f960, 0x20, 0x20, 0xda201, 0x72f2b0, 0x130f8bc)
    /__w/arduino-cli/arduino-cli/legacy/builder/builder.go:210 +0xb8
github.com/arduino/arduino-cli/legacy/builder.(*Builder).Run(0x130fa88, 0x1040960, 0x801c70, 0x26f26d0)
    /__w/arduino-cli/arduino-cli/legacy/builder/builder.go:117 +0xa98
github.com/arduino/arduino-cli/legacy/builder.RunBuilder(...)
    /__w/arduino-cli/arduino-cli/legacy/builder/builder.go:226
github.com/arduino/arduino-cli/commands/compile.Compile(0x7ff7b0, 0x1030040, 0x130fe74, 0x7f8f48, 0x10100d0, 0x7f8f48, 0x10100d8, 0x1027810, 0x55bc00, 0x1, ...)
    /__w/arduino-cli/arduino-cli/commands/compile/compile.go:172 +0x10e4
github.com/arduino/arduino-cli/cli/compile.run(0x10cbcc0, 0x112d340, 0x1, 0x7)
    /__w/arduino-cli/arduino-cli/cli/compile/compile.go:96 +0x208
github.com/spf13/cobra.(*Command).execute(0x10cbcc0, 0x112d2c0, 0x7, 0x8, 0x10cbcc0, 0x112d2c0)
    /github/home/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x204
github.com/spf13/cobra.(*Command).ExecuteC(0xcbdfa8, 0x407b8, 0x5dc5ec, 0x10000e0)
    /github/home/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x234
github.com/spf13/cobra.(*Command).Execute(...)
    /github/home/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
    /__w/arduino-cli/arduino-cli/main.go:28 +0x24
```

=> In cores, search for `avr` and install the `arduino:avr` core.

This problem has already been reported on the `arduino-cli` GitHub.

**Comment by Renaud11232** [comment]
This is fixed in arduino-cli 0.7.0 but arduino 0.7.0 has a few bugs that needs to be fixed

**Comment by Renaud11232** [comment]
0.7.1 fixed the issues.

**Comment by Renaud11232** [comment]
I'll keep this issue open until I decide to drop support for arduinocli prior to 0.7.x
